apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: todomarch
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kunalborkar2001/todomarch:latest
          ports:
            - containerPort: 8085
          env:
            - name: JWT_SECRET
              value: "romanreignsrocks"
            - name: MONGODB_URI
              value: "mongodb+srv://kunalborkar2001:pveoINdiVlZx2wEm@kunalsmongo.5raphyd.mongodb.net/taskManager"
            - name: PORT
              value: "8085"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: todomarch
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80       # service port
      targetPort: 8085 # container port
      nodePort: 30080 # optional, must be in range 30000–32767
