apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: todomarch
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kunalborkar2001/todomarch-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: todomarch
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 3000 # container port
      nodePort: 30081 # optional, you can choose between 30000–32767
